import test from "node:test";
import assert from "node:assert/strict";
import {APPROVED_LAYOUT_VERSION,CANVAS,buildAttendanceReportSvg} from "../src/attendance-image.mjs";
const N=["Điều Văn Mạnh","Nguyễn Thị Thục Anh","Vũ Đình Tuệ","Bùi Duy Hoàng","Nguyễn Thành Long","Trần Thanh Bình","Lê Thị Phương Linh","Lê Đăng Hiếu"];
function morning(){return{kind:"attendance_business_report",slot:"morning_1230",date:"2026-10-02",timezone:"Asia/Ho_Chi_Minh",employees:N.map((name,i)=>i===7?{name,morning:null,status_code:"not_recorded_morning"}:{name,morning:{in:"08:00",out:"12:00",minutes:240},status_code:"recorded"})};}
function daily(){return{kind:"attendance_business_report",slot:"daily_2105",date:"2026-10-01",timezone:"Asia/Ho_Chi_Minh",employees:N.map(name=>({name,sessions:[{in:"08:00",out:"12:00",minutes:240},{in:"13:30",out:"18:30",minutes:300}],total_minutes:540,total_display:"9h00",status_code:"recorded"}))};}
test("V4 locks one 3:4 mockup-fidelity canvas",()=>{assert.equal(APPROVED_LAYOUT_VERSION,"ATTENDANCE_IMAGE_V4_MOCKUP_FIDELITY_2026_10_02");assert.deepEqual(CANVAS,{width:1080,height:1440});});
test("morning V4 keeps header KPI chart donut and detail table on one page",()=>{const svg=buildAttendanceReportSvg(morning());assert.match(svg,/width="1080" height="1440"/);assert.match(svg,/BÁO CÁO/);assert.match(svg,/CHẤM CÔNG — CA SÁNG/);assert.match(svg,/GIỜ CÔNG CA SÁNG THEO NHÂN SỰ/);assert.match(svg,/TỔNG QUAN CA SÁNG/);assert.match(svg,/CHI TIẾT CHẤM CÔNG CA SÁNG/);assert.match(svg,/Điều Văn Mạnh/);assert.doesNotMatch(svg,/STACORP/);assert.doesNotMatch(svg,/<image\b/i);});
test("daily V4 visually separates morning and afternoon",()=>{const svg=buildAttendanceReportSvg(daily());assert.match(svg,/CHẤM CÔNG — CẢ NGÀY/);assert.match(svg,/CA SÁNG/);assert.match(svg,/CA CHIỀU/);assert.match(svg,/08:00–12:00/);assert.match(svg,/13:30–18:30/);assert.match(svg,/9h00/);});
test("V4 rejects non-8-person roster",()=>{const r=morning();r.employees.pop();assert.throws(()=>buildAttendanceReportSvg(r),/exactly 8 employees/);});
