import test from "node:test";
import assert from "node:assert/strict";
import {APPROVED_LAYOUT_VERSION,OVERVIEW_CANVAS,DETAIL_CANVAS,buildAttendanceReportSvgs} from "../src/attendance-image.mjs";
const N=["Điều Văn Mạnh","Nguyễn Thị Thục Anh","Vũ Đình Tuệ","Bùi Duy Hoàng","Nguyễn Thành Long","Trần Thanh Bình","Lê Thị Phương Linh","Lê Đăng Hiếu"];
function morning(){return{kind:"attendance_business_report",slot:"morning_1230",date:"2026-10-02",timezone:"Asia/Ho_Chi_Minh",employees:N.map((name,i)=>i===7?{name,morning:null,status_code:"not_recorded_morning"}:{name,morning:{in:"08:00",out:"12:00",minutes:240},status_code:"recorded"})};}
function daily(){return{kind:"attendance_business_report",slot:"daily_2105",date:"2026-10-01",timezone:"Asia/Ho_Chi_Minh",employees:N.map(name=>({name,sessions:[{in:"08:00",out:"12:00",minutes:240},{in:"13:30",out:"18:30",minutes:300}],total_minutes:540,total_display:"9h00",status_code:"recorded"}))};}
test("V3 locks mobile-first two-image canvases",()=>{assert.equal(APPROVED_LAYOUT_VERSION,"ATTENDANCE_IMAGE_V3_MOBILE_FIRST_2026_10_02");assert.deepEqual(OVERVIEW_CANVAS,{width:1080,height:1350});assert.deepEqual(DETAIL_CANVAS,{width:1080,height:1620});});
test("morning V3 separates overview and readable detail",()=>{const v=buildAttendanceReportSvgs(morning());assert.match(v.overview,/width="1080" height="1350"/);assert.match(v.overview,/GIỜ CÔNG CA SÁNG THEO NHÂN SỰ/);assert.match(v.detail,/width="1080" height="1620"/);assert.match(v.detail,/CHI TIẾT 8 NHÂN SỰ/);assert.match(v.detail,/Điều Văn Mạnh/);assert.match(v.detail,/Công sáng/);assert.doesNotMatch(v.overview,/STACORP/);assert.doesNotMatch(v.detail,/<image\b/i);});
test("daily V3 makes morning and afternoon explicit per employee",()=>{const v=buildAttendanceReportSvgs(daily());assert.match(v.overview,/TỔNG CÔNG THEO NHÂN SỰ/);assert.match(v.detail,/CA SÁNG/);assert.match(v.detail,/CA CHIỀU/);assert.match(v.detail,/08:00–12:00/);assert.match(v.detail,/13:30–18:30/);assert.match(v.detail,/9h00/);});
test("V3 rejects non-8-person roster",()=>{const r=morning();r.employees.pop();assert.throws(()=>buildAttendanceReportSvgs(r),/exactly 8 employees/);});
